### ISSUE TITLE
Firefox: Website

### ISSUE THREAD

**Issue by ceci-bowles** [Pinestorm/saas-website#8]
Looking good, the calendar is great!
A few suggestions:
- maybe have the navigation linked pages spread across the top of the website and push the social media badges on the footer only
- centre icons in cards on the products page
- have a gutter on the form page to push apart the sections

**Comment by Pinestorm** [comment]
Thanks for the feedback, I've fixed the icons and the form. As for the navigation I think I am going to leave it this time, I spend hours last night trying to do what you suggested and just could not figure it out.
