### ISSUE TITLE
UC Browser Android

### ISSUE THREAD

**Issue by sander-aaron** [Pinestorm/saas-website#9]
- Maybe centre text in nav buttons
- There is a bit of space (possibly padding-right on the body) that makes a small line of blue down the right edge
- Would centre icons on Products page
- Would remove space that separates the title of the package from what the package contains because with it, it looks a bit disjointed
- The illustration at the end of the sign-up page is 10/10
Overall your website is really well put together, good job

**Comment by Pinestorm** [comment]
Thanks for the feedback, fixed everything you listed
